### ISSUE TITLE
Tag version

### ISSUE THREAD

**Issue by romaricdrigon** [WeCodePixels/premailer-bundle#1]
Hi,

It would be great to have some versions. At least to lock things in `composer.json`.
Could you please tag a version?

Thanks!

**Comment by liviucmg** [comment]
Sure thing, I will tag this as 0.1.0. By the way, does this still work properly? I haven't really used it in over a year. :)

**Comment by romaricdrigon** [comment]
It still works properly width SF2 2.6, yes :)
